import Footer from "./components/Footer";
import "./globals.css";
import { inter } from "@/utils/fonts";

export const metadata = {
  title: "Glocal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body cz-shortcut-listen="true" className={inter.className}>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
